In [62]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf


In [63]:
#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

EIN                                      NAME APPLICATION_TYPE  \
0  10520599              BLUE KNIGHTS MOTORCYCLE CLUB              T10   
1  10531628    AMERICAN CHESAPEAKE CLUB CHARITABLE TR               T3   
2  10547893        ST CLOUD PROFESSIONAL FIREFIGHTERS               T5   
3  10553066            SOUTHSIDE ATHLETIC ASSOCIATION               T3   
4  10556103  GENETIC RESEARCH INSTITUTE OF THE DESERT               T3   

        AFFILIATION CLASSIFICATION      USE_CASE  ORGANIZATION  STATUS  \
0       Independent          C1000    ProductDev   Association       1   
1       Independent          C2000  Preservation  Co-operative       1   
2  CompanySponsored          C3000    ProductDev   Association       1   
3  CompanySponsored          C2000  Preservation         Trust       1   
4       Independent          C1000     Heathcare         Trust       1   

      INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0              0                      N     5000              1  
1         1-9999                      N   108590              1  
2              0                      N     5000              0  
3    10000-24999                      N     6692              1  
4  100000-499999                      N   142590              1

In [64]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.

app_clean_df=application_df.drop(columns= {"EIN", "NAME"})
app_clean_df.head(2)

APPLICATION_TYPE  AFFILIATION CLASSIFICATION      USE_CASE  ORGANIZATION  \
0              T10  Independent          C1000    ProductDev   Association   
1               T3  Independent          C2000  Preservation  Co-operative   

   STATUS INCOME_AMT SPECIAL_CONSIDERATIONS  ASK_AMT  IS_SUCCESSFUL  
0       1          0                      N     5000              1  
1       1     1-9999                      N   108590              1

 My target variable is is_successful
 the remaining variables are my features.


In [65]:
# Determine the number of unique values in each column.
app_clean_df.nunique()


APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [66]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = app_clean_df['APPLICATION_TYPE'].value_counts()
app_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [67]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_counts[app_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    app_clean_df['APPLICATION_TYPE'] = app_clean_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
app_clean_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [68]:
# Look at CLASSIFICATION value counts for binning
class_counts = app_clean_df['CLASSIFICATION'].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...  
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [69]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [70]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    app_clean_df['CLASSIFICATION'] = app_clean_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
app_clean_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [71]:
# Convert categorical data to numeric with `pd.get_dummies`
app_clean_df = pd.get_dummies(app_clean_df)
app_clean_df.head()

STATUS  ASK_AMT  IS_SUCCESSFUL  APPLICATION_TYPE_Other  \
0       1     5000              1                       0   
1       1   108590              1                       0   
2       1     5000              0                       0   
3       1     6692              1                       0   
4       1   142590              1                       0   

   APPLICATION_TYPE_T10  APPLICATION_TYPE_T19  APPLICATION_TYPE_T3  \
0                     1                     0                    0   
1                     0                     0                    1   
2                     0                     0                    0   
3                     0                     0                    1   
4                     0                     0                    1   

   APPLICATION_TYPE_T4  APPLICATION_TYPE_T5  APPLICATION_TYPE_T6  ...  \
0                    0                    0                    0  ...   
1                    0                    0                    0  ...   
2                    0                    1                    0  ...   
3                    0                    0                    0  ...   
4                    0                    0                    0  ...   

   INCOME_AMT_1-9999  INCOME_AMT_10000-24999  INCOME_AMT_100000-499999  \
0                  0                       0                         0   
1                  1                       0                         0   
2                  0                       0                         0   
3                  0                       1                         0   
4                  0                       0                         1   

   INCOME_AMT_10M-50M  INCOME_AMT_1M-5M  INCOME_AMT_25000-99999  \
0                   0                 0                       0   
1                   0                 0                       0   
2                   0                 0                       0   
3                   0                 0                       0   
4                   0                 0                       0   

   INCOME_AMT_50M+  INCOME_AMT_5M-10M  SPECIAL_CONSIDERATIONS_N  \
0                0                  0                         1   
1                0                  0                         1   
2                0                  0                         1   
3                0                  0                         1   
4                0                  0                         1   

   SPECIAL_CONSIDERATIONS_Y  
0                         0  
1                         0  
2                         0  
3                         0  
4                         0  

[5 rows x 44 columns]

In [72]:
app_clean_df.columns

Index(['STATUS', 'ASK_AMT', 'IS_SUCCESSFUL', 'APPLICATION_TYPE_Other',
       'APPLICATION_TYPE_T10', 'APPLICATION_TYPE_T19', 'APPLICATION_TYPE_T3',
       'APPLICATION_TYPE_T4', 'APPLICATION_TYPE_T5', 'APPLICATION_TYPE_T6',
       'APPLICATION_TYPE_T7', 'APPLICATION_TYPE_T8',
       'AFFILIATION_CompanySponsored', 'AFFILIATION_Family/Parent',
       'AFFILIATION_Independent', 'AFFILIATION_National', 'AFFILIATION_Other',
       'AFFILIATION_Regional', 'CLASSIFICATION_C1000', 'CLASSIFICATION_C1200',
       'CLASSIFICATION_C2000', 'CLASSIFICATION_C2100', 'CLASSIFICATION_C3000',
       'CLASSIFICATION_Other', 'USE_CASE_CommunityServ', 'USE_CASE_Heathcare',
       'USE_CASE_Other', 'USE_CASE_Preservation', 'USE_CASE_ProductDev',
       'ORGANIZATION_Association', 'ORGANIZATION_Co-operative',
       'ORGANIZATION_Corporation', 'ORGANIZATION_Trust', 'INCOME_AMT_0',
       'INCOME_AMT_1-9999', 'INCOME_AMT_10000-24999',
       'INCOME_AMT_100000-499999', 'INCOME_AMT_10M-50M', 'INCOME_AMT_1M-5M

In [73]:
# Split our preprocessed data into our features and target arrays
x = app_clean_df.drop(columns=['IS_SUCCESSFUL']).values
y = app_clean_df['IS_SUCCESSFUL'].values

In [74]:
x[0]

array([   1, 5000,    0,    1,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    1,    0,    0,    0,    1,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    1,    1,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    1,    0])

In [75]:
y

array([1, 1, 0, ..., 0, 1, 0])

In [76]:
# split into training and testing data
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [77]:
len(x_train[0])

43

In [78]:
x_test[0]

array([    1, 24145,     0,     0,     0,     1,     0,     0,     0,
           0,     0,     0,     0,     1,     0,     0,     0,     1,
           0,     0,     0,     0,     0,     0,     0,     0,     1,
           0,     0,     0,     0,     1,     0,     0,     1,     0,
           0,     0,     0,     0,     0,     1,     0])

In [79]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
x_scaler = scaler.fit(x_train)

# Scale the data
x_train_scaled = x_scaler.transform(x_train)
x_test_scaled = x_scaler.transform(x_test)
print(x_train_scaled[0])

[ 0.01394306 -0.0304623  -0.08829654 -0.12758082 -0.1798502   0.52293914
 -0.21906968 -0.19161061 -0.19269822 -0.1464315  -0.1487688  -0.91978219
 -0.04500615  0.92606521 -0.03055899 -0.00881785 -0.01870803 -1.01086606
 -0.4039708   2.15607526 -0.24045219 -0.24698637 -0.26391185 -0.10659407
 -0.06553264 -0.00881785  0.47306117 -0.44819376 -0.65597487 -0.1179556
 -0.03529198  0.67940482  0.63397891 -0.1464315  -0.1247184  -0.33048965
 -0.08204493 -0.16884151 -0.34871842 -0.06340457 -0.0715443   0.03055899
 -0.03055899]


In [80]:
# Create a keras sequentila model
nn_model = tf.keras.models.Sequential()

In [81]:
# Add first dense layer including the input layer (hidden layer)
nn_model.add(tf.keras.layers.Dense(units=5, activation="relu", input_dim =43))
nn_model.add(tf.keras.layers.Dense(units=5, activation="relu"))

In [82]:
# output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

In [83]:
# Check the structure of the model
nn_model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 5)                 220       
                                                                 
 dense_13 (Dense)            (None, 5)                 30        
                                                                 
 dense_14 (Dense)            (None, 1)                 6         
                                                                 
Total params: 256 (1.00 KB)
Trainable params: 256 (1.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [84]:
# Compile the model
nn_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [85]:
# Train the model
fit_model = nn_model.fit(x_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.6546 - accuracy: 0.6149
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5877 - accuracy: 0.7170
Epoch 3/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5721 - accuracy: 0.7219
Epoch 4/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5662 - accuracy: 0.7233
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5627 - accuracy: 0.7277
Epoch 6/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5604 - accuracy: 0.7294
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5586 - accuracy: 0.7297
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5577 - accuracy: 0.7299
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5567 - accuracy: 0.7312
Epoch 10/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5560 - accura

In [86]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(x_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5550 - accuracy: 0.7297 - 528ms/epoch - 2ms/step
Loss: 0.5549569725990295, Accuracy: 0.72967928647995


In [89]:
# Export our model to HDF5 file
nn_model.save('alphabet_soup.h5')